apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: app-java
          image: jodelnord/usine-logicielle-java:55ecbb273e2a3e89cf7b216ac8150a4b2ca83d06
          ports:
            - containerPort: 8080
