apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: app-java
          image: jodelnord/usine-logicielle-java:a6fa46dbf81d1db3cbf67cc1e043c6381daf21c9
          ports:
            - containerPort: 8080
