apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
        - name: app-java
          image: jodelnord/usine-logicielle-java:0e791d191509d225a60340d9f266ac6133c33647
          ports:
            - containerPort: 8080
