- name: Déploiement application Java Docker
  hosts: nodes
  become: yes
  serial: 1 # déploiement progressif (pro)

  vars:
    image_name: "ton-dockerhub/usine-logicielle-java:latest"
    container_name: app-java

  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Supprimer ancien container
      docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Télécharger image Docker
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Lancer container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        recreate: yes
        ports:
          - "8080:8080"

    - name: Vérifier container
      command: docker ps
      register: docker_output

    - name: Afficher résultat
      debug:
        var: docker_output.stdout
