[nodes]
vm2 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_common_args='-o ProxyJump=vagrant@100.83.54.15 -o StrictHostKeyChecking=no'
vm3 ansible_host=192.168.56.13 ansible_user=vagrant ansible_ssh_common_args='-o ProxyJump=vagrant@100.83.54.15 -o StrictHostKeyChecking=no'

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'